AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: hw3
Resources:
  nyucloudhw2cfphoto:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'nyucloudhw3'
      VersioningConfiguration:
        Status: Enabled